name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Execute dry run
        required: true
        type: boolean
        default: false

jobs:
  release-dry-run:
    if: github.repository_owner == '3liz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Fetch yapt
        run: |
          curl ${{ vars.YAPT_REPOSITORY_URL }} | tar -xzf -        
      
      - name: Fetch current changelog
        run: |
          ./yapt-pkg  changelog >> release.md
          cat release.md

      - name: Package and deploy the zip
        env:
            DRY_RUN_OPT: ${{ inputs.dry_run == true && '--dry-run' || '' }}
        run: >
          ./yapt-pkg -v package --publish ${{ env.DRY_RUN_OPT }}
          --osgeo-username "${{ secrets.OSGEO_USERNAME }}"
          --osgeo-password "${{ secrets.OSGEO_PASSWORD }}"

      # Note: this action fail if this is not a tag ref
      - name: Create release on Github
        if: ${{ inputs.dry_run == false }}
        uses: ncipollo/release-action@v1.20.0
        with:
          bodyFile: release.md
          artifacts: "*.zip"
          token: ${{ secrets.BOT_HUB_TOKEN }}


